name: Test and build

on:
  push:
    branches: [ "**" ]
    tags: [ "v*" ]
  pull_request:
    branches: [master]

jobs:
  test-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        #- 2.7
        - 3.6
        - 3.7
        - 3.8
        - 3.9
        - "3.10.0-beta.4"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -r requirements-tests.txt
        python -m pip install --no-deps client/
        python -m pip install --no-deps protobuf/
        python -m pip install hiku
        python -m pip install grpclib
        python -m pip install grpcio
        python -m pip install protobuf
    - name: Run tests
      run: |
        py.test -c client/pytest.ini